export const dbURI = process.env.DB_URI;
export const dbPassword = process.env.DB_PASSWORD;
export const jwtSecret = process.env.JWT_SECRET;
export const twilioSID = process.env.TWILIO_SID;
export const twilioToken = process.env.TWILIO_TOKEN;
export const twilioNumber = process.env.TWILIO_NUMBER;
export const mailjetKey = process.env.MAILJET_KEY;
export const mailjetSecret = process.env.MAILJET_SECRET;
export const stripeKey: string = process.env.STRIPE_KEY as string;
